print("welcome to the tip calculator")
bill = (input("what was the total bill?"))
percentage = (input("what percentage tip would you like to give? 10, 12, or 15 ?"))
bill_int = int(bill)
percentage_int = int(percentage)
bill_with_percentage = (bill_int * (1 + percentage_int/100))
Amount_people = input("how many people split the bill")
amount_people_int = int(Amount_people)
bill_per_person = (bill_with_percentage / amount_people_int)
print (round (bill_per_person,2))